<a href="https://colab.research.google.com/github/ashok9847/customer-sales-data-analysis/blob/main/data_cleaning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import pandas as pd
import matplotlib.pyplot as plt

In [5]:
df=pd.read_csv('messy_customer_sales_data.csv')

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10200 entries, 0 to 10199
Data columns (total 12 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Customer_ID         9177 non-null   object
 1   Name                10200 non-null  object
 2   Gender              9174 non-null   object
 3   Age                 9249 non-null   object
 4   City                9184 non-null   object
 5   Signup_Date         10200 non-null  object
 6   Last_Purchase_Date  9188 non-null   object
 7   Purchase_Amount     9179 non-null   float64
 8   Feedback_Score      9177 non-null   float64
 9   Email               10200 non-null  object
 10  Phone_Number        10200 non-null  int64
 11  Country             9468 non-null   object
dtypes: float64(2), int64(1), object(9)
memory usage: 956.4+ KB

In [7]:
#check the statistic part now
stat=df.describe()
#roundoff data
stat.round()

       Purchase_Amount  Feedback_Score  Phone_Number
count           9179.0          9177.0  1.020000e+04
mean           29090.0             5.0  4.979974e+09
std           208697.0             3.0  2.902593e+09
min             -500.0             1.0  9.208990e+05
25%            12295.0             3.0  2.449157e+09
50%            24330.0             5.0  4.988639e+09
75%            37130.0             8.0  7.510448e+09
max          9999999.0            10.0  9.994402e+09

In [8]:
df.isnull().sum()#gives all the null value
# df.isnull().count() -- not count() coz it will take
# all the data no matter there it t,f,string ,int
# df[df.isnull()].shape -- #we cant do this

Customer_ID           1023
Name                     0
Gender                1026
Age                    951
City                  1016
Signup_Date              0
Last_Purchase_Date    1012
Purchase_Amount       1021
Feedback_Score        1023
Email                    0
Phone_Number             0
Country                732
dtype: int64

In [9]:
df.shape

(10200, 12)

In [10]:
df.dropna().shape #drops any cell if it consists of null data

(4528, 12)

In [11]:
df[df.duplicated()].shape

(15, 12)

In [12]:
df[df.duplicated()]

,Customer_ID,Name,Gender,Age,City,Signup_Date,Last_Purchase_Date,Purchase_Amount,Feedback_Score,Email,Phone_Number,Country
2032,CUST2755,Casey Campbell,male,NaN,Hyderabad,2023-12-01,2024-11-04,11778.0,3.0,joseph49@example.com,3844741384,India
3191,NaN,Travis Schneider,f,51.0,NaN,2025-04-20,2025-02-28,48750.0,5.0,bianca77@example.net,7623118785,India
4312,CUST8305,Stanley Cain,FEMALE,51.0,Bangalore,2023-08-14,2024-11-01,11432.0,6.0,calderonbrenda@example.org,4889366037,India
5611,CUST6288,Jonathon Kim,male,46.0,Chennai,2023-11-22,2025-03-21,3301.0,6.0,tparker@example.com,5266662560,India
5680,CUST2695,Lisa Durham,NaN,46.0,Chennai,2021-04-18,2024-10-10,6511.0,3.0,andrew34@example.com,2235480149,India
5899,CUST8841,Amanda Hill,NaN,34.0,chennai,2022-09-11,2025-03-13,42092.0,4.0,ryanriley@example.net,3466026146,India
6070,CUST10780,Emily Smith,NaN,23.0,Kolkata,2023-12-09,2024-10-28,18027.0,5.0,perezchristopher@example.com,3032282870,India
6240,CUST9745,David Morales,NaN,56.0,NaN,2023-02-18,2024-12-14,49107.0,7.0,juliaknapp@example.com,9436163110,India
6425,CUST4631,George Villa,m,26.0,Mumbai,2022-05-21,2025-06-17,NaN,8.0,davidmarquez@example.com,8869465862,India
6498,CUST1711,Stephanie Elliott,NaN,44.0,MUMBAI,2023-05-17,2025-07-12,11349.0,9.0,nfischer@example.com,3270872546,NaN
7118,CUST9380,Paul Wilson,MALE,42.0,Bangalore,2025-07-31,2025-09-21,2696.0,5.0,steven57@example.net,6835989909,India
8392,CUST1436,Ralph Anderson,female,33.0,Kolkata,2022-10-21,2025-04-24,42870.0,NaN,vcosta@example.com,3739220307,India
9155,CUST10040,Mark Taylor,NaN,43.0,Delhi,2021-04-16,2025-01-13,37793.0,6.0,tinaknapp@example.org,9898365939,India
9960,CUST6220,John Rodriguez,male,51.0,Hyderabad,2021-03-28,2025-01-22,27102.0,10.0,laurahart@example.com,7462990833,India
10140,CUST4367,Amber Kennedy,F,61.0,Bangalore,2023-11-05,2025-01-10,40711.0,8.0,kellifox@example.com,5600790669,India

In [13]:
df['Customer_ID']

0         CUST4371
1         CUST5957
2         CUST3754
3         CUST2934
4         CUST5683
           ...
10195    CUST10767
10196          NaN
10197     CUST6315
10198     CUST4812
10199     CUST6588
Name: Customer_ID, Length: 10200, dtype: object

In [14]:
# df['Customer_ID'=='CUST2755'] # this is wrong  coz we r comparing cloumn_id with particular column name
df[df['Customer_ID'] == 'CUST2755']#here u can see dupliacted is used to find the completely same itemset

,Customer_ID,Name,Gender,Age,City,Signup_Date,Last_Purchase_Date,Purchase_Amount,Feedback_Score,Email,Phone_Number,Country
1874,CUST2755,Casey Campbell,male,NaN,Hyderabad,2023-12-01,2024-11-04,11778.0,3.0,joseph49@example.com,3844741384,India
2032,CUST2755,Casey Campbell,male,NaN,Hyderabad,2023-12-01,2024-11-04,11778.0,3.0,joseph49@example.com,3844741384,India

In [15]:
df['Customer_ID'].value_counts()# it acts like group by #use to count the total number of each ell value in customer_id
# df['Customer_ID'].count()#use to count the total number of rows in the customer_id
#here value_counts() automatically counts
# and sorts the data form highest to lowest
# here primary key must be unique , some of the data is not duplicate coz some cell might
#have the diff vavlue to we check using the specific column that is primary key

Customer_ID
CUST10800    2
CUST6588     2
CUST9062     2
CUST1852     2
CUST5472     2
            ..
CUST1585     1
CUST3825     1
CUST2446     1
CUST9867     1
CUST4362     1
Name: count, Length: 9000, dtype: int64

In [16]:
df[df['Customer_ID']=='CUST6588']
# here u can see that the f and female is there so this can be find from the duplicate

,Customer_ID,Name,Gender,Age,City,Signup_Date,Last_Purchase_Date,Purchase_Amount,Feedback_Score,Email,Phone_Number,Country
7080,CUST6588,David Potter,FEMALE,34.0,Hyderabad,2020-10-12,2025-06-27,35211.0,10.0,kochjonathan@example.org,1926206725,India
10199,CUST6588,David Potter,female,34.0,HYDERABAD,2020-10-12,2025-06-27,35211.0,10.0,kochjonathan@example.org,1926206725,India

In [17]:
for col in df.columns:
  if df[col].nunique()<20:
    print(df[col].value_counts())
    print('-'*50)

Gender
f         1184
M         1171
m         1163
F         1157
MALE      1131
female    1128
male      1121
FEMALE    1119
Name: count, dtype: int64
--------------------------------------------------
City
Kolkata       820
Mumbai        812
Chennai       784
Bangalore     773
Hyderabad     770
Delhi         763
CHENNAI       404
KOLKATA       395
MUMBAI        393
hyderabad     384
bangalore     383
DELHI         378
delhi         369
BANGALORE     363
HYDERABAD     360
mumbai        352
chennai       343
kolkata       338
Name: count, dtype: int64
--------------------------------------------------
Feedback_Score
2.0     952
4.0     947
7.0     938
6.0     927
3.0     913
8.0     912
1.0     907
9.0     903
10.0    901
5.0     877
Name: count, dtype: int64
--------------------------------------------------
Country
India    7132
IND       793
india     772
InDia     771
Name: count, dtype: int64
--------------------------------------------------

In [18]:
df.dropna(subset=['Customer_ID'], inplace=True)
# find any rows where the ID is missing (NaN or null), and permanently delete those entire rows from your DataFrame

In [19]:
df['Age'].unique()

array(['52.0', '51.0 years', '62.0', '40.0', '41.0', nan, '18.0',
       '43.0 years', '40.0 years', '26.0', '32.0', '22.0', '59.0', '65.0',
       '61.0', '31.0', '54.0 years', '55.0', '69.0', '61.0 years', '24.0',
       '63.0', '19.0', '50.0', '56.0', '36.0', '68.0', '43.0', '38.0',
       '27.0', '57.0 years', '23.0', '25.0', '66.0', '28.0', '30.0',
       '46.0', '48.0', '20.0', '37.0', '67.0', '51.0', '35.0', '58.0',
       '29.0', 'nan years', '39.0', '49.0', '47.0', '42.0', '44.0',
       '64.0', '53.0', '60.0', '59.0 years', '45.0', '21.0', '34.0',
       '54.0', '48.0 years', '46.0 years', '33.0', '57.0', '30.0 years',
       '58.0 years', '35.0 years', '34.0 years', '69.0 years', '250',
       '19.0 years', '27.0 years', '53.0 years', '65.0 years',
       '66.0 years', '44.0 years', '49.0 years', '25.0 years',
       '23.0 years', '62.0 years', '41.0 years', '33.0 years',
       '28.0 years', '22.0 years', '20.0 years', '42.0 years',
       '45.0 years', '3', '63.0 years', '37.0 years', '38.0 years',
       '55.0 years', '18.0 years', '36.0 years', '67.0 years',
       '29.0 years', '39.0 years', '31.0 years', '47.0 years',
       '52.0 years', '-10', '60.0 years', '24.0 years', '26.0 years',
       '21.0 years', '64.0 years', '50.0 years', '68.0 years',
       '32.0 years', '56.0 years'], dtype=object)

In [20]:
# int(df['Age'])
# df['Age']
import re
def extract(age):
  age_num=re.findall('[0-9]+',str(age))
  if len(age_num)>0:
    return age_num[0]
  else:
    return age

df['Age']=df['Age'].apply(lambda x:extract(x))
df['Age']

0        52
1        51
2        62
3        40
4        41
         ..
10194    40
10195    35
10197    25
10198    55
10199    34
Name: Age, Length: 9177, dtype: object

In [21]:

# df_age=df['Age'].isnull()
# df_age
# df.isnull().sum()
# df_age=df[df['Age'].notnull()]['Age']
# df_age = df[df['Age'] != 'nan']['Age']
# df_age.isnull().sum()

# df_age.isnull().sum()
# age_median=int(df['Age'].dropna().astype('int64').median())
# age_median
df['Age'].unique()

array(['52', '51', '62', '40', '41', nan, '18', '43', '26', '32', '22',
       '59', '65', '61', '31', '54', '55', '69', '24', '63', '19', '50',
       '56', '36', '68', '38', '27', '57', '23', '25', '66', '28', '30',
       '46', '48', '20', '37', '67', '35', '58', '29', 'nan years', '39',
       '49', '47', '42', '44', '64', '53', '60', '45', '21', '34', '33',
       '250', '3', '10'], dtype=object)

In [22]:
df['Age'] = pd.to_numeric(df['Age'], errors='coerce')#converted every string into num and if we encounter with any value with is not num then it will return NAN
#coz we alread have nan in my table so it will return flaot
df['Age'].unique()
age_median=int(df['Age'].dropna().astype('int64').median())
#here we have to cualte the median() without the null values we do dropna

df['Age'] = df['Age'].fillna(age_median)
#fill the nan with the median
df['Age'] = df['Age'].astype('int64')
# change the str type into num now
df['Age'].unique()
df['Age'].dtype

dtype('int64')

In [23]:
price_median=int(df['Purchase_Amount'].median())
price_median

24268

In [24]:
df['Purchase_Amount']=df['Purchase_Amount'].fillna(price_median)
df['Purchase_Amount'] = df['Purchase_Amount'].astype('int64')

df['Purchase_Amount'].unique()

array([26944, 44152, 31745, ..., 24167, 43832, 18827])

In [25]:
df.isnull().sum()

Customer_ID             0
Name                    0
Gender                934
Age                     0
City                  918
Signup_Date             0
Last_Purchase_Date    914
Purchase_Amount         0
Feedback_Score        905
Email                   0
Phone_Number            0
Country               664
dtype: int64

In [26]:
for col in ['Gender','City','Feedback_Score','Country']:
  df[col]=df[col].fillna(df[col].mode()[0])

In [27]:
for col in ['Last_Purchase_Date']:
  df[col] = df[col].fillna(method='ffill')

/tmp/ipykernel_4091/3063046388.py:2: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df[col] = df[col].fillna(method='ffill')

# Fixing the inconsistent formatting

In [28]:
df['Gender'].unique()

array(['m ', 'M', 'F', 'FEMALE', 'f ', 'male', 'MALE', 'female'],
      dtype=object)

In [29]:
df['Gender'].str.lower().unique()#all into lower

array(['m ', 'm', 'f', 'female', 'f ', 'male'], dtype=object)

In [30]:
df['Gender']=df['Gender'].str.lower().str.strip()#all into lower
df['Gender'].unique()

array(['m', 'f', 'female', 'male'], dtype=object)

In [31]:
df['Gender']=df['Gender'].replace({'m':'Male','f':'female'})
df['Gender']

0          Male
1          Male
2        female
3        female
4        female
          ...
10194    female
10195    female
10197      Male
10198    female
10199    female
Name: Gender, Length: 9177, dtype: object

In [32]:
df['City']

0           KOLKATA
1           Kolkata
2         hyderabad
3         hyderabad
4           CHENNAI
            ...
10194       Kolkata
10195         delhi
10197     hyderabad
10198       Kolkata
10199     HYDERABAD
Name: City, Length: 9177, dtype: object

In [33]:
# df['City']=df['City'].str.lower().str.strip()
# df['City'].unique()

In [34]:
df['Country'].str.lower().str.strip().unique()

array(['india', 'ind'], dtype=object)

In [35]:
df['Country']=df['Country'].str.lower().str.strip()
df['Country']=df['Country'].replace({'ind':'india'})
df['Country'].unique()

array(['india'], dtype=object)

In [36]:
df[df.duplicated()].shape

(50, 12)

In [38]:
df_backup = df.copy()

df.drop_duplicates(inplace=True)
df

,Customer_ID,Name,Gender,Age,City,Signup_Date,Last_Purchase_Date,Purchase_Amount,Feedback_Score,Email,Phone_Number,Country
0,CUST4371,Paul Wilson,Male,52,KOLKATA,2025-06-26,2025-05-17,26944,1.0,peckvictoria@example.com,2131107701,india
1,CUST5957,Jason Thomas,Male,51,Kolkata,2021-02-17,2025-07-22,44152,2.0,owensanthony@example.com,1080761560,india
2,CUST3754,Brittney Martinez,female,62,hyderabad,2023-11-05,2024-12-08,31745,2.0,tara39@example.org,8981006345,india
3,CUST2934,Brenda Pierce,female,40,hyderabad,2022-03-13,2025-10-02,39674,1.0,berrynancy@example.org,8228064204,india
4,CUST5683,Matthew Carroll,female,41,CHENNAI,2024-04-05,2024-12-15,24268,8.0,denise84@example.org,2665569480,india
...,...,...,...,...,...,...,...,...,...,...,...,...
10194,CUST6146,Cody Thompson,female,40,Kolkata,2024-08-21,2024-10-26,35101,1.0,mitchellrivera@example.net,6380823112,india
10195,CUST10767,Robert Lewis,female,35,delhi,2020-12-08,2025-01-25,24167,9.0,barrycrane@example.net,5004696571,india
10197,CUST6315,Joshua Martinez,Male,25,hyderabad,2022-02-15,2025-01-11,43832,2.0,kelli74@example.org,8147428496,india
10198,CUST4812,Sarah Miller,female,55,Kolkata,2021-03-16,2025-05-14,18827,10.0,dawn84@example.org,2987564247,india
10199,CUST6588,David Potter,female,34,HYDERABAD,2020-10-12,2025-06-27,35211,10.0,kochjonathan@example.org,1926206725,india